package org.example.quanlynhahang.controllers;

import javafx.fxml.FXML;
import javafx.scene.control.*;
import javafx.stage.Stage;
import org.example.quanlynhahang.database.DatabaseConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.Normalizer;
import java.util.regex.Pattern;

public class AddDishController {
    @FXML private TextField txtFoodName;
    @FXML private TextField txtPrice;
    @FXML private TextArea txtDescription;
    @FXML private ComboBox<String> cbCategory;

    @FXML
    public void initialize() {
        cbCategory.getItems().addAll("Món chính", "Khai vị", "Đồ uống", "Tráng miệng");
    }

    // Hàm phụ để biến "Bánh Tráng Trộn" thành "banhtrangtron"
    private String removeAccent(String s) {
        String temp = Normalizer.normalize(s, Normalizer.Form.NFD);
        Pattern pattern = Pattern.compile("\\p{InCombiningDiacriticalMarks}+");
        return pattern.matcher(temp).replaceAll("").replace("đ", "d").replace("Đ", "D").replace(" ", "").toLowerCase();
    }

    @FXML
    private void handleAdd() {
        String autoGeneratedId = "MON" + (int)(Math.random() * 10000);

        // TỚ ĐÃ SỬA: Thêm cột HINH_ANH vào câu lệnh INSERT
        String sql = "INSERT INTO MONAN (MA_MON, TEN_MON, DANH_MUC, GIA_TIEN, MO_TA, HINH_ANH) VALUES (?, ?, ?, ?, ?, ?)";

        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            String foodName = txtFoodName.getText();
            // Tự tạo tên file ảnh dựa trên tên món: ví dụ "banhtrangtron.png"
            String imageName = removeAccent(foodName) + ".png";

            pstmt.setString(1, autoGeneratedId);
            pstmt.setString(2, foodName);
            pstmt.setString(3, cbCategory.getValue());
            pstmt.setDouble(4, Double.parseDouble(txtPrice.getText()));
            pstmt.setString(5, txtDescription.getText());
            pstmt.setString(6, imageName); // Lưu tên ảnh vào cột thứ 6

            pstmt.executeUpdate();
            handleCancel();

        } catch (Exception e) {
            System.out.println("Lỗi lưu món: " + e.getMessage());
            Alert alert = new Alert(Alert.AlertType.ERROR);
            alert.setTitle("Lỗi");
            alert.setHeaderText(null);
            alert.setContentText("Không thể lưu món: " + e.getMessage());
            alert.showAndWait();
        }
    }

    @FXML
    private void handleCancel() {
        if (txtFoodName.getScene() != null) {
            Stage stage = (Stage) txtFoodName.getScene().getWindow();
            stage.close();
        }
    }
}